name: '⁉️ Scoping Form'
description: This issue template is designed to capture the outcomes.
title: '[Customer]: Scoping Form'
labels:
  - 👥 scoping
body:
  - type: dropdown
    attributes:
      label: Responsible Party
      description: Name Responsible
      multiple: false
      options:
        - '@megamanics'
        - '@vinayski'
    validations:
      required: true
