name: Move Repo Issue to Org Project - Legacy
on:
  issues:
    types:
      - opened
  workflow_dispatch: {}    
jobs:
  addIssueToProject:
    #if: contains(github.event.issue.name, 'Scoping Form')
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event context
        env:
          GH_EVENT: ${{ toJson(github.event) }}
        run: echo "$GH_EVENT"
      - name: Add To GitHub Projects Beta
        uses: megamanics/add-to-project@main
        with:
          # URL of the project to add issues to
          # outside https://github.com/orgs/github/projects/6144
          project-url: https://github.com/orgs/github/projects/6144
          github-token: ${{ secrets.TOKEN1 }}
