name: Move OoO Issue to Project
on:
  issues:
    types:
      - opened
  workflow_dispatch: {}    
jobs:
  addOoOIssueToProject:
    if: contains(github.event.issue.title, 'OoO')
    runs-on: ubuntu-latest
    steps:
      - name: Add To GitHub Projects Beta
        uses: megamanics/add-to-project@main
        with:
          # URL of the project to add issues to
          project-url: https://github.com/users/megamanics/projects/2
          github-token: ${{ secrets.TOKEN1 }}
